# Generated by Django 2.0.7 on 2018-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180711_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='products/'),
            preserve_default=False,
        ),
    ]
