# Generated by Django 2.0.7 on 2018-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
